# Generated by Django 2.2 on 2020-04-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_additionalimage_bb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bb',
            new_name='Bbmain',
        ),
    ]
