# Generated by Django 2.2 on 2020-04-03 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200401_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalImage',
            new_name='DopImage',
        ),
    ]
